# Generated by Django 5.2.2 on 2025-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سعر الشراء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البيع'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='سعر البيع'),
        ),
    ]
