# Generated by Django 5.2.2 on 2025-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='company_files/', verbose_name='ملف'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='value_type',
            field=models.CharField(choices=[('STRING', 'نص'), ('INTEGER', 'رقم صحيح'), ('FLOAT', 'رقم عشري'), ('BOOLEAN', 'صحيح/خطأ'), ('JSON', 'JSON'), ('FILE', 'ملف')], default='STRING', max_length=20, verbose_name='نوع القيمة'),
        ),
    ]
