# Generated by Django 5.2.2 on 2025-06-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_goodsissuedonloan_goodsissuedonloanitem'),
    ]

    operations = [
    ]
