# Generated by Django 5.2.2 on 2025-06-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_itemtransformation_itemtransformationinput_and_more'),
    ]

    operations = [
    ]
