# Generated by Django 5.2.2 on 2025-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_physicalinventory_physicalinventoryitem'),
    ]

    operations = [
    ]
