# Generated by Django 5.2.2 on 2025-06-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0010_add_printer'),
        ('inventory', '0012_auto_20250607_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='رقم جرد أول المدة')),
                ('date', models.DateField(verbose_name='تاريخ أول المدة')),
                ('fiscal_year', models.CharField(max_length=10, verbose_name='السنة المالية')),
                ('period_name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('total_items', models.IntegerField(default=0, verbose_name='عدد الأصناف')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='إجمالي الكميات')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي القيمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('posted_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='سعر الصرف')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opening_inventories', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='definitions.currency', verbose_name='العملة')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opening_inventories', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='definitions.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'جرد بضاعة أول المدة',
                'verbose_name_plural': 'جرد بضاعة أول المدة',
                'ordering': ['-date', '-id'],
                'unique_together': {('warehouse', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='OpeningInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('opening_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='كمية أول المدة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي القيمة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الدفعة')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع في المخزن')),
                ('condition', models.CharField(choices=[('NEW', 'جديد'), ('GOOD', 'جيد'), ('FAIR', 'مقبول'), ('POOR', 'ضعيف'), ('DAMAGED', 'تالف')], default='GOOD', max_length=20, verbose_name='الحالة')),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'ممتاز'), ('B', 'جيد جداً'), ('C', 'جيد'), ('D', 'مقبول')], max_length=20, verbose_name='درجة الجودة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recorded_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='definitions.item', verbose_name='الصنف')),
                ('opening_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.openinginventory', verbose_name='جرد أول المدة')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'صنف جرد أول المدة',
                'verbose_name_plural': 'أصناف جرد أول المدة',
                'ordering': ['item__name'],
                'unique_together': {('opening_inventory', 'item', 'batch_number')},
            },
        ),
    ]
