# Generated by Django 5.2.2 on 2025-06-08 14:16

import definitions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0010_add_printer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_name_english', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة بالإنجليزية')),
                ('logo', models.ImageField(blank=True, help_text='يفضل أن يكون الشعار بصيغة PNG أو JPG وبحجم 200x200 بكسل', null=True, upload_to=definitions.models.company_logo_upload_path, verbose_name='شعار الشركة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=20, verbose_name='السجل التجاري')),
                ('app_name', models.CharField(default='نظام الحسابات', max_length=100, verbose_name='اسم التطبيق')),
                ('app_version', models.CharField(default='1.0.0', max_length=20, verbose_name='إصدار التطبيق')),
                ('items_per_page', models.IntegerField(default=25, verbose_name='عدد العناصر في الصفحة')),
                ('date_format', models.CharField(choices=[('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%Y-%m-%d', 'YYYY-MM-DD')], default='%d/%m/%Y', max_length=20, verbose_name='تنسيق التاريخ')),
                ('session_timeout_minutes', models.IntegerField(default=60, verbose_name='انتهاء الجلسة (دقيقة)')),
                ('password_min_length', models.IntegerField(default=8, verbose_name='الحد الأدنى لطول كلمة المرور')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='تفعيل النسخ الاحتياطي التلقائي')),
                ('backup_frequency_days', models.IntegerField(default=7, verbose_name='تكرار النسخ الاحتياطي (أيام)')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات البريد الإلكتروني')),
                ('sms_notifications_enabled', models.BooleanField(default=False, verbose_name='تفعيل إشعارات الرسائل النصية')),
                ('default_report_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='تنسيق التقارير الافتراضي')),
                ('print_logo_on_reports', models.BooleanField(default=True, verbose_name='طباعة الشعار في التقارير')),
                ('print_company_info', models.BooleanField(default=True, verbose_name='طباعة معلومات الشركة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='definitions.currency', verbose_name='العملة الافتراضية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
