# Generated by Django 5.2.2 on 2025-06-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0011_add_company_settings'),
    ]

    operations = [
    ]
