# Generated by Django 5.2.2 on 2025-06-08 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0012_auto_20250608_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='السعر')),
                ('rate_type', models.CharField(choices=[('BUY', 'شراء'), ('SELL', 'بيع'), ('AVERAGE', 'متوسط'), ('OFFICIAL', 'رسمي')], default='AVERAGE', max_length=20, verbose_name='نوع السعر')),
                ('source', models.CharField(max_length=100, verbose_name='المصدر')),
                ('recorded_date', models.DateTimeField(verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.currency', verbose_name='العملة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'تاريخ سعر العملة',
                'verbose_name_plural': 'تاريخ أسعار العملات',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='EgyptianBankRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='سعر الشراء')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='سعر البيع')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('source_url', models.URLField(blank=True, verbose_name='مصدر البيانات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.currency', verbose_name='العملة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'سعر صرف البنك',
                'verbose_name_plural': 'أسعار صرف البنوك',
                'ordering': ['bank_name', 'currency__code'],
                'unique_together': {('currency', 'bank_name')},
            },
        ),
    ]
